package main

const (
	rootShortDescription    = "ArchGuard Analyzer - architectural analyzer tool powered by AI"
	analyzeCommandUse       = "analyze"
	analyzeCommandShort     = "Analyze project architecture and report violations"
	projectFlagName         = "project"
	projectFlagShorthand    = "p"
	projectFlagDefault      = "."
	projectFlagDescription  = "Path to the project codebase"
	rulesFlagName           = "rules"
	rulesFlagShorthand      = "r"
	rulesFlagDescription    = "Path to YAML rules file"
	docsFlagName            = "docs"
	docsFlagShorthand       = "d"
	docsFlagDescription     = "Path to project documentation"
	outputJSONFlagName      = "output-json"
	outputJSONFlagShorthand = "j"
	outputJSONFlagDefault   = "report.json"
	outputJSONFlagDesc      = "JSON report path"
	outputMDFlagName        = "output-md"
	outputMDFlagShorthand   = "m"
	outputMDFlagDefault     = "report.md"
	outputMDFlagDesc        = "Markdown report path"
	providerFlagName        = "provider"
	providerFlagDesc        = "LLM provider: anthropic / gemini / openai"
	apiKeyFlagName          = "api-key"
	apiKeyFlagDesc          = "API key (or use .env)"
	modelFlagName           = "model"
	modelFlagDesc           = "Model override"
	maxToolCallsFlagName    = "max-tool-calls"
	maxToolCallsFlagDesc    = "Max tool calls"
	timeoutFlagName         = "timeout"
	timeoutFlagDesc         = "Analysis timeout"
	interactiveFlagName     = "interactive"
	interactiveFlagDesc     = "Prompt for consent-required tool calls"
	resumeFlagName          = "resume"
	resumeFlagDesc          = "Path to a previous report.json to continue analysis from (skips already-analyzed files)"

	estimateCommandUse   = "estimate"
	estimateCommandShort = "Estimate tool-call budget and number of runs required for a project"
)
